services:
  mapr:
    platform: linux/amd64
    image: erdincka/maprdemo:latest
    container_name: mapr
    restart: unless-stopped
    environment:
      - clusterName=mapr.demo
      - isSecure=true
      - MAPR_TZ=Europe/London
      - TZ=Europe/London
      - NIFI_WEB_PROXY_HOST=docker:12443
      - NIFI_VERSION=1.28.0
      - NIFI_USER=admin
      # Following password needs to be min 12 chars
      - NIFI_PASSWORD=Admin123.Admin123.
    ports:
      - "8443:8443"  ## optional for MCS
      - "2222:22"  ## optional for SSH
      - "12443:12443" ## optional for NiFi
      - "3000:3000" ## optional for Grafana
    cap_add:
      - SYS_ADMIN
    privileged: true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint: ["/entrypoint.sh"]
