services:
  sparkflows:
    platform: linux/amd64
    container_name: sparkflows
    image: sparkflows/fire:py_3.5.2_3.3.1
    ports:
      - "8080:8080"
      # - "9443:9443"
    environment:
      - FIRE_VERSION=3.1.0
      - KEYSTORE_PASSWORD=12345678
      - FIRE_HTTP_PORT=8080
      - FIRE_HTTPS_PORT=9443
    restart: unless-stopped
